export default {
  meta: {
    name: '液态玻璃',
    author: 'Ethan',
    label: 'light',
    extend: '',
  },
  colors: {
    'primary-color': '#1d1d1f',
    'primary-color-end': '#3a3a3c',
    'second-color': '#6e6e73',
    'third-color': '#8e8e93',
    'button-text-color': '#ffffff',

    'danger-color': '#3a3a3c',
    'succeed-color': '#1d1d1f',

    'icon-nav-bar-right': '#6e6e73',
    'unimportant-icon-color': '#0000002e',

    'status-bar-background-color': '#f5f5f7cc',
    'background-color': '#f5f5f7',
    'nav-bar-color': '#f5f5f7b8',
    'tab-bar-color': '#ffffffc7',
    'popup-color': '#ffffffd6',
    'divider-color': '#00000014',
    'card-color': '#ffffffa8',
    'dialog-color': '#ffffffd4',
    'switch-close-background-color': '#00000014',
    'switch-active-background-color': '#1d1d1f',
    'compare-item-background-color': '#ffffff80',
    'picker-mask-near-color': '#f5f5f766',
    'picker-mask-far-color': '#f5f5f7',

    'primary-text-color': '#1d1d1f',
    'second-text-color': '#3a3a3c',
    'comment-text-color': '#636366',
    'lowest-text-color': '#737378',

    'img-brightness': '0',
    'nav-bar-blur': '28px',
    'tab-bar-blur': '28px',
    'sticky-title-blur': '28px',
    'glass-stroke': '#ffffffc7',
    'glass-highlight': '#ffffffeb',
    'glass-fill': '#ffffff99',
    'glass-sheen': '#ffffffcc',
    'sub-progress-fill': '#0000000d',
    'sub-progress-edge': '#00000026',
    'sub-progress-opacity': '1',

    'compare-tag-text-color': '#3a3a3c',
    'compare-tag-background-color': '#00000012',
  },
};
